config/routes.rb
Calapps::Application.routes.draw do
  get "password_resets/new"

  get "welcome/about"
  get "welcome/success"
  get "welcome/construction"
  get "users/new"
  get 'tags/:tag', to: 'calapps#index', as: :tag

  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', :to => 'sessions#destroy',     via: :delete
  match 'contact' => 'contact#new', :as => 'contact', :via => :get
  match '/contact' => 'contact#create', :as => 'contact', :via => :post

  resources :users
  
  resources :calapps do
    collection do
      get 'search'
      get 'feed'
    end
    member do
      put 'archive'
      put 'approve'
    end
    resources :reviews, :only => [:create, :new, :destroy]
  end
  
  resources :sessions
  resources :password_resets
  
  root :to => 'calapps#index'

end

app/models/calapp.rb
class Calapp < ActiveRecord::Base
	#belongs_to :user
  has_many :reviews
  has_many :users, through: :reviews

  scope :approved, -> { where(approved: true) }
  scope :pending, -> { where(approved: false) }
  scope :archived, -> { where(archived: true) }
  scope :active, -> { where(archived: false) }
  scope :search_query, lambda { |query| where("upper(name) like ? or upper(description) like ? or upper(creator) like ?", query, query, query) }
  scope :name_search, lambda { |name| where("upper(name) like ?", name) }
  scope :creator_search, lambda { |creator| where("upper(creator) like ?", creator) }
  scope :description_search, lambda { |description| where("upper(description) like ?", description) }
  scope :category_search, lambda { |category| where("upper(category) like ?", category) }
  scope :rated_at_least, lambda { |threshold| joins(:reviews).group('calapps.id').having(['AVG(reviews.review_rating >= ?', threshold]) }
  scope :order_by_rating, -> { includes(:reviews).group('calapps.id, reviews.id').order('AVG(reviews.review_rating) IS NULL, AVG(reviews.review_rating) DESC') }

	attr_accessible  :name, :URL, :creator, :description, :tag_list, :created_location, 
    :user_email, :category, :image, :screenshot1, :screenshot2, :screenshot3, :screenshot4, 
    :screenshot5, :archived, :news

	#For tagging
	acts_as_taggable 

	#For validating the name of the actual application
	validates :name, :presence => true, length: {:within => 3..25}, 
  			uniqueness: { case_sensitive: false }

  	#For validating that there is a creator for the application
	validates :creator, :presence => true

	#For validatidating that there must be a cateogry for the application be filed in
	validates :category, :presence => true, inclusion: { in: %w(Academic Career Collaboration Commerce Food Health Miscellaneous Mobile Multipurpose),
    message: "%{value} is not a valid category" }

    #For validating there must be an actual URL 
	validates :URL, :presence => true, 
  			uniqueness: { case_sensitive: false }

  #For the uploading of the thumbnail
  mount_uploader :image, ImageUploader

  mount_uploader :screenshot1, ImageUploader
  mount_uploader :screenshot2, ImageUploader
  mount_uploader :screenshot3, ImageUploader
  mount_uploader :screenshot4, ImageUploader
  mount_uploader :screenshot5, ImageUploader

  @@changes = []

  def self.changes
    @@changes
  end

  def self.add_change(change)
    @@changes.push(change)
  end

  def self.categories
    ['Academic', 'Career', 'Collaboration', "Commerce", "Food", "Health", "Miscellaneous", "Mobile", "Multipurpose"]
  end

  def rating
    sum = 0.0
    total = 0
    self.reviews.each do |review|
      sum += review.review_rating
      total += 1
    end
    if total == 0
      return sum
    else
      return sum/total
    end
  end

  def self.top_four(category)
    calapps = approved.active.category_search("%"+category.upcase+"%").order_by_rating[0,4]
    if calapps.length == 0
      []
    else
      calapps
    end
  end
end

app/controllers/calapps_controller.rb
class CalappsController < ApplicationController 
  respond_to :json

  def search
    @calapps = Calapp.approved
    @calapps = @calapps.name_search("%"+params[:name].upcase+"%") if params[:name]
    @calapps = @calapps.creator_search("%"+params[:creator].upcase+"%") if params[:creator]
    @calapps = @calapps.description_search("%"+params[:description].upcase+"%") if params[:description]
    @calapps = @calapps.category_search("%"+params[:category].upcase+"%") if params[:category]
    @calapps = @calapps.tagged_with(params[:tag]) if params[:tag]
    render :partial => "calapps/search.json"
  end

  def show 
    @calapp = Calapp.find_by_id(params[:id])
  end 

  #This is solely for the use of the gallery page
  def index
    @pending = session[:pending] = params[:pending]
    @archived = session[:archived] = params[:archived]

    if @pending
      @calapps = Calapp.pending.active.order(:name)
    elsif @archived
      @calapps = Calapp.archived.order(:name)
    else
      @calapps = Calapp.approved.active.order(:name)
    end

    @query = session[:search_query] = params[:search_query]

    if ! [nil, ""].include?(@query)
      query = "%"+@query.upcase+"%"
      @calapps = @calapps.search_query(query)
    end

    @category = session[:category] = params[:category]
    
    if @category
      @calapps = @calapps.category_search("%"+params[:category].upcase+"%")
    end

    @tag = session[:tag] = params[:tag]

    if @tag
      @calapps = @calapps.tagged_with(params[:tag])
    end
 
    if @pending or @archived or @tag or @category or @query
      @home = false
    else
      @home = true
      @calapp = Calapp
    end
  end

  def new 
    if not signed_in?
      redirect_to calapps_path
    else
      @calapp = Calapp.new
    end
  end 

  def create 
    @calapp = Calapp.new(params[:calapp])
    @calapp.user_email = current_user.email
    if is_admin? or berkeley_user?
      @calapp.approved = true
    end
    if @calapp.save
      Calapp.add_change("#{current_user.email} created #{@calapp.name}")
      redirect_to '/calapps', notice: (is_admin? or berkeley_user?) ? "#{@calapp.name} was successfully created." : "#{@calapp.name} submitted for approval."
    else
      flash[:error] = @calapp.errors.full_messages
      render action: 'new'
    end
  end 

  def edit 
    @calapp = Calapp.find_by_id(params[:id])
    if not signed_in? or (@calapp.user_email != current_user.email and !is_admin?)
      redirect_to calapps_path
    end     
  end 

  def update
    @calapp = Calapp.find_by_id(params[:id])
    if not signed_in? or (@calapp.user_email != current_user.email and !is_admin?)
      redirect_to calapps_path
    else
      @calapp.campus_approved = params[:calapp][:campus_approved]
      @calapp.approved = params[:calapp][:approved]
      params[:calapp].delete(:campus_approved)
      params[:calapp].delete(:approved)
      if @calapp.save and @calapp.update_attributes(params[:calapp])
        Calapp.add_change("#{current_user.email} updated #{@calapp.name}")
        flash[:notice] = "#{@calapp.name} was successfully updated."
        redirect_back_or @calapp
      else
        flash[:error] = @calapp.errors.full_messages
        render 'edit'
      end
    end
  end

  def destroy
    if is_admin?
      @calapp = Calapp.find_by_id(params[:id])
      @calapp.destroy
      Calapp.add_change("#{current_user.email} deleted #{@calapp.name}")
      redirect_to calapps_path, notice: "#{@calapp.name} was sucessfully deleted."
    else
      redirect_to :back
    end
  end

  def archive
    if is_admin?
      calapp = Calapp.find_by_id(params[:id])
      if calapp.archived
        calapp.archived = false
        flash[:notice] = "#{calapp.name} was successfully unarchived."
      else
        calapp.archived = true
        flash[:notice] = "#{calapp.name} was successfully archived."
      end
      calapp.save
    end
    redirect_to :back
  end

  def approve
    if is_admin?
      calapp = Calapp.find_by_id(params[:id])
      calapp.approved = true
      calapp.save
      flash[:notice] = "#{calapp.name} was successfully approved."
    end
    redirect_to :back
  end 

  def feed
    if is_admin?
      @changes = Calapp.changes
    else
      redirect_to :back
    end
  end

end 

app/helpers/calapps_helper.rb
module CalappsHelper
	def thumbnail_url(calapp)
		if calapp.image.present?
			calapp.image
		else
			calapp.image = 'http://www.advancingjustice-alc.org/sites/asian-law-caucus/files/styles/publication-landing/public/default_images/aj-aai-publication-default-thumbnail_0.gif?itok=8wySC9YR'
		end
	end

	def screenshot1_url(calapp)
		if calapp.screenshot1.present?
			calapp.screenshot1
		else
			calapp.screenshot1 = ''
		end
	end

	def screenshot2_url(calapp)
		if calapp.screenshot2.present?
			calapp.screenshot2
		else
			calapp.screenshot2 = ''
		end
	end

	def screenshot3_url(calapp)
		if calapp.screenshot3.present?
			calapp.screenshot3
		else
			calapp.screenshot3 = ''
		end
	end

	def screenshot4_url(calapp)
		if calapp.screenshot4.present?
			calapp.screenshot4
		else
			calapp.screenshot4 = ''
		end
	end

	def screenshot5_url(calapp)
		if calapp.screenshot5.present?
			calapp.screenshot5
		else
			calapp.screenshot5 = ''
		end
	end

	def screenshot_present?(calapp)
		screenshot1_url(calapp).present? or screenshot2_url(calapp).present? or screenshot3_url(calapp).present? or screenshot4_url(calapp).present? or screenshot5_url(calapp).present?
	end
	
end

app/views/calapps/_form.html.haml
= form_for @calapp, :html => { :class => 'form-horizontal' } do |f|
  .control-group
    = f.label :name, :class => 'control-label'
    .controls
      = f.text_field :name, :class => 'text_field'
  .control-group
    = f.label :URL, :class => 'control-label'
    .controls
      = f.text_field :URL, :class => 'text_field'
  .control-group
    = f.label :creator, :class => 'control-label'
    .controls
      = f.text_field :creator, :class => 'text_field'
  .control-group
    = f.label :description, :class => 'control-label'
    .controls
      = f.text_area :description, :class => 'text_area'
  .form-actions
    = f.submit nil, :class => 'btn btn-primary'
    = link_to t('.cancel', :default => t("helpers.links.cancel")), calapps_path, :class => 'btn'

app/views/calapps/_left_column.html.haml
.left-column-container.column.gallery
  .search-bar-container.left-container>
    %h2 Search
    = form_tag calapps_path, :method => :get, :id => 'search_form' do
      = hidden_field_tag :tag, session[:tag] if session[:tag]
      = hidden_field_tag :pending, session[:pending] if session[:pending]
      = hidden_field_tag :archived, session[:archived] if session[:archived]
      = hidden_field_tag :category, session[:category] if session[:category]
      .search-input-container.input-group
        %input{:class => 'form-control search-bar', :type => 'text', :placeholder => 'Search for an app...', :name => 'search_query', :value => session[:search_query]}
        %span{:class =>"input-group-btn"}>
          <input type="submit" class="btn btn-default search-submit" value="Go">
  .categories-container.left-container
    %h2 Categories
    %ul
      - @categories.each do |category|
        %li.category-container
          - if session[:category] == category
            <b>
          = link_to "#{category}", calapps_path(:search_query => session[:search_query], :tag => session[:tag], :pending => session[:pending], :archived => session[:archived], :category => category)
          - if session[:category] == category
            </b>
  .tags-container.left-container
    %h2 Tags
    %ul
      .tags
        - @all_tags.each do |tag|
          - if Calapp.tagged_with(tag).length > 0
            %li.tag-container{:data => {:tag => tag}}>
              = form_tag calapps_path, :method => :get, :id => 'tag_form' do
                = hidden_field_tag :search_query, session[:search_query] if session[:search_query]
                = hidden_field_tag :tag, tag
                = hidden_field_tag :pending, session[:pending] if session[:pending]
                = hidden_field_tag :archived, session[:archived] if session[:archived]
                = hidden_field_tag :category, session[:category] if session[:category]
                - if session[:tag] == tag
                  <input type="submit" class="btn btn-default label-danger tag" value="#{tag}" />
                - else
                  <input type="submit" class="btn btn-default label-default tag" value="#{tag}" />
  - if session[:tag] or session[:search_query] or session[:category]
    .reset-container
      = link_to 'Reset Search', '/', :class => 'btn btn-default reset-search'
    %hr

app/views/calapps/_list_calapp_card.html.haml
.list-calapp-wrapper
  .calapp-container{:data => {:calapp_id => calapp.id}}
    .calapp-info
      .image-wrapper
        =link_to image_tag(thumbnail_url(calapp)), calapp_path(calapp), :id => "#{calapp.name}"
      .content
        =link_to calapp_path(calapp), :class => "title" do
          =calapp.name
        .actions
          -if is_admin?
            -if !calapp.approved
              = link_to 'Approve', approve_calapp_path(calapp), :method => :put, :class => "btn btn-primary btn-xs"
            = link_to 'Edit', edit_calapp_path(calapp), {:method => :get, :class => "btn btn-default btn-xs"}
            - if calapp.archived
              = link_to 'Unarchive', archive_calapp_path(calapp), {:method => :put, :confirm => 'Are you sure?', :class => "btn btn-primary btn-xs"}
            - else
              = link_to 'Archive', archive_calapp_path(calapp), {:method => :put, :confirm => 'Are you sure?', :class => "btn btn-danger btn-xs"}
            |

          =calapp.creator
          |
          Rating:
          - if calapp.rating != 0
            = "%.1f" % calapp.rating.to_s
          - else
            N/A

app/views/calapps/_square_calapp_card.html.haml
.calapp-wrapper
  = link_to calapp_path(calapp) do
    .calapp-container{:data => {:calapp_id => calapp.id}}
      .calapp-info
        .img-wrapper
          = image_tag(thumbnail_url(calapp))
        .title= truncate(calapp.name, :length => 34)

app/views/calapps/alphabetize.html.haml
%h1 Alphabetized View
%a.button.dropdown.small{:href=>"#", :data=>{:dropdown=>"drop"}} Actions
%ul#drop.f-dropdown{:data=>{"dropdown-content".to_sym=>true}}
  %li= link_to "List View", "/calapps"
  %li= link_to "Grid View", "/gallery"
  - if is_admin?
    - if @pending or @archived
      %li= link_to "Show Approved", "/calapps"
    - if !@archived
      %li= link_to "Show Archived", "/calapps?archived=>true"
    - if !@pending
      %li= link_to "Show Pending", "/calapps?pending=>true"
  -if signed_in?
    %li= link_to "Add an Application", new_calapp_path
- @calapps.keys.sort.each do |starting_letter|
  %hr
  %h3=starting_letter
  %hr
  %ul.small-block-grid-4
    - @calapps[starting_letter].each do |calapp|
      %li
        =link_to calapp_path(calapp), :class => "th" do
          = image_tag thumbnail_url(calapp)
          .caption
            %h3= calapp.name
            %p
              %em= calapp.creator

app/views/calapps/edit.html.haml
.container
  = render 'shared/error_messages'
  
  = form_for @calapp do |f|
    %fieldset
      %legend Edit Existing CalApp
      #name.form-group
        = f.label :name, 'Name of Application', :class => "control-label reserve-label"
        .reserve-input
          = f.text_field :name

      #image.form-group
        = f.label :image, "Upload Thumbnail", :class => "control-label reserve-label"
        .reserve-input
          = f.file_field :image

      %h3 Upload Screenshots
      #screenshot1.form-group
        = f.label :screenshot1, "Upload Screenshot", :class => "control-label reserve-label"
        .reserve-input
          = f.file_field :screenshot1

      #screenshot2.form-group
        = f.label :screenshot2, "Upload Screenshot", :class => "control-label reserve-label"
        .reserve-input
          = f.file_field :screenshot2

      #screenshot3.form-group
        = f.label :screenshot3, "Upload Screenshot", :class => "control-label reserve-label"
        .reserve-input
          = f.file_field :screenshot3

      #screenshot4.form-group
        = f.label :screenshot4, "Upload Screenshot", :class => "control-label reserve-label"
        .reserve-input
          = f.file_field :screenshot4

      #screenshot5.form-group
        = f.label :screenshot5, "Upload Screenshot", :class => "control-label reserve-label"
        .reserve-input
          = f.file_field :screenshot5

      #url.form-group
        = f.label :URL, "Application URL", :class => "control-label reserve-label"
        .reserve-input
          = f.url_field :URL

      #creator.form-group
        = f.label :creator, "Creator(s)", :class => "control-label reserve-label"
        .reserve-input
          = f.text_field :creator

      #created.form-group
        = f.label :created_location, "Event created", :class => "control-label reserve-label"
        .reserve-input
          = f.text_field :created_location

      #category.form-group
        = f.label :category, "Category", :class => "control-label reserve-label"
        .reserve-input
          = f.select :category, @categories, :include_blank => true

      #description.form-group
        = f.label :description, "Description", :class => "control-label reserve-label"
        .reserve-input
          = f.text_area :description
      
      #news.form-group
        = f.label :news, "News & Updates", :class => "control-label reserve-label"
        .reserve-input
          = f.text_area :news

      #tags.form-group
        = f.label :tag_list, "Tags (separate by commas)", :class => "control-label reserve-label"
        .reserve-input
          = f.text_field :tag_list

      -if is_admin?
        #owner.form-group
          = f.label :user_email, "Owner email", :class => "control-label reserve-label"
          .reserve-input
            = f.text_field :user_email

        #campus-approved.form-group
          = f.label :campus_approved, "Endorse the app?", :class => "control-label reserve-label"
          .reserve-input
            = f.select :campus_approved, {"Yes" => true, "No" => false}

        #approved.form-group
          = f.label :approved, "Approved?", :class => "control-label reserve-label"
          .reserve-input
            = f.select :approved, {"Yes" => true, "No" => false}

        #archived.form-group
          = f.label :archived, "Archive", :class => "control-label reserve-label"
          .reserve-input
            = f.select :archived, {"Yes" => true, "No" => false}

    = link_to 'Back to App Details', calapp_path(@calapp), :class => "btn btn-default"
    = link_to 'Back to App List', calapps_path, :class => "btn btn-default"
    = f.submit 'Update', :class => "btn btn-primary"

app/views/calapps/feed.html.haml
.container
  %h1 CalApps Update Feed
  %ul
  - if @changes.length > 0
    - @changes.reverse.each do |change|
      %li= change
  - else
    %li No updates

app/views/calapps/gallery.html.haml
%h1 Gallery Gridview
%a.button.dropdown.small{:href=>"#", :data=>{:dropdown=>"drop"}} Actions
%ul#drop.f-dropdown{:data=>{"dropdown-content".to_sym=>true}}
  %li= link_to "List View", "/calapps"
  %li= link_to "Alphabetized View", "/list"
  - if is_admin?
    - if @pending or @archived
      %li= link_to "Show Approved", "/calapps"
    - if !@archived
      %li= link_to "Show Archived", "/calapps?archived=>true"
    - if !@pending
      %li= link_to "Show Pending", "/calapps?pending=>true"
  -if signed_in?
    %li= link_to "Add an Application", new_calapp_path



%ul.small-block-grid-4
  - @calapps.each do |calapp|
    %li
      =link_to calapp_path(calapp), :class => "th" do
        = image_tag thumbnail_url(calapp)
        .caption
          %h3= calapp.name
          %p
            %em= calapp.creator

app/views/calapps/index.html.haml
#is-admin{"data-is-admin" => "#{is_admin?}"}

.container.gallery
  .content
    = render partial: 'left_column'
    .right-column-container.column.gallery
      .header
        .btn-group#toolbar
          %a.btn.btn-default#card-view-link{:href => "#card-view", "data-toggle" => "tab"}
            %i.fa.fa-th-large
          %a.btn.btn-default#list-view-link{:href => "#list-view", "data-toggle" => "tab"}
            %i.fa.fa-list
        - if is_admin?
          = render "settings"
        - if signed_in?
          = link_to 'Add App', new_calapp_path(), :class => "btn btn-primary add-calapp"

      #calapp-cards.tab-content
        - if @calapps.length > 0
          - if @home and !is_admin?
            .tab-pane#card-view
              - @categories.each do |category|
                - if !@calapp.top_four(category).empty?
                  .category-card-row
                    %fieldset
                      %legend #{category}
                      - @calapp.top_four(category).each do |calapp|
                        = render partial: 'square_calapp_card', locals: {calapp: calapp}
            .tab-pane#list-view
              - @categories.each do |category|
                - if !@calapp.top_four(category).empty?
                  .category-list-row
                    %fieldset
                      %legend #{category}
                      - @calapp.top_four(category).each do |calapp|
                        = render partial: 'list_calapp_card', locals: {calapp: calapp}
          - else
            .tab-pane#card-view
              - @categories.each do |category|
                - if !@calapps.category_search("%"+category.upcase+"%").empty?
                  .category-card-row
                    %fieldset
                      %legend #{category}
                      - @calapps.category_search("%"+category.upcase+"%").each do |calapp|
                        = render partial: 'square_calapp_card', locals: {calapp: calapp}
            .tab-pane#list-view
              - @categories.each do |category|
                - if !@calapps.category_search("%"+category.upcase+"%").empty?
                  .category-list-row
                    %fieldset
                      %legend #{category}
                      - @calapps.category_search("%"+category.upcase+"%").each do |calapp|
                        = render partial: 'list_calapp_card', locals: {calapp: calapp}

        - else
          = render partial: 'no_results'

app/views/calapps/new.html.haml
.container
  = render 'shared/error_messages'
       
  = form_for @calapp, :html => {:multipart => true} do |f|
    %fieldset
      %legend Add Application
      #name.form-group
        = f.label :name, 'Name of Application', :class => "control-label reserve-label"
        .reserve-input
          = f.text_field :name

      #image.form-group
        = f.label :image, "Upload Thumbnail", :class => "control-label reserve-label"
        .reserve-input
          = f.file_field :image

      %h3 Upload Screenshots
      #screenshot1.form-group
        = f.label :screenshot1, "Upload Screenshot", :class => "control-label reserve-label"
        .reserve-input
          = f.file_field :screenshot1

      #screenshot2.form-group
        = f.label :screenshot2, "Upload Screenshot", :class => "control-label reserve-label"
        .reserve-input
          = f.file_field :screenshot2

      #screenshot3.form-group
        = f.label :screenshot3, "Upload Screenshot", :class => "control-label reserve-label"
        .reserve-input
          = f.file_field :screenshot3

      #screenshot4.form-group
        = f.label :screenshot4, "Upload Screenshot", :class => "control-label reserve-label"
        .reserve-input
          = f.file_field :screenshot4

      #screenshot5.form-group
        = f.label :screenshot5, "Upload Screenshot", :class => "control-label reserve-label"
        .reserve-input
          = f.file_field :screenshot5

      #url.form-group
        = f.label :URL, "Application URL", :class => "control-label reserve-label"
        .reserve-input
          = f.url_field :URL

      #creator.form-group
        = f.label :creator, "Creator(s)", :class => "control-label reserve-label"
        .reserve-input
          = f.text_field :creator

      #created.form-group
        = f.label :created_location, "Event created", :class => "control-label reserve-label"
        .reserve-input
          = f.text_field :created_location

      #category.form-group
        = f.label :category, "Category", :class => "control-label reserve-label"
        .reserve-input
          = f.select :category, @categories, :include_blank => true

      #description.form-group
        = f.label :description, "Description", :class => "control-label reserve-label"
        .reserve-input
          = f.text_area :description

      #news.form-group
        = f.label :news, "News & Updates", :class => "control-label reserve-label"
        .reserve-input
          = f.text_area :news

      #tags.form-group
        = f.label :tag_list, "Tags (separate by commas)", :class => "control-label reserve-label"
        .reserve-input
          = f.text_field :tag_list
    = link_to 'Back', calapps_path, :class =>"btn btn-default"
    = f.submit 'Submit', :class => "btn btn-primary", :url => calapp_path(f)

app/views/calapps/show.html.haml
.container
  %h1 #{@calapp.name}
  = image_tag(thumbnail_url(@calapp), :class => "image")

  %fieldset
    %legend Information
    Created by
    = @calapp.creator
    %div
      = link_to @calapp.URL, @calapp.URL
    %hr
    Category:
    = @calapp.category
    - if @calapp.campus_approved
      %hr
      Campus Endorsed
      = image_tag "/assets/cal.jpeg", :height=> "30px", :width=>"30px"
  %hr
  - if screenshot_present?(@calapp)
    %h4 Screenshots
    %ul.clearing-thumbs{:data => {:clearing => true}}
      -if screenshot1_url(@calapp).present?
        %li
          = image_tag screenshot1_url(@calapp)
      -if screenshot2_url(@calapp).present?
        %li
          = image_tag screenshot2_url(@calapp)
      -if screenshot3_url(@calapp).present?
        %li
          = image_tag screenshot3_url(@calapp)
      -if screenshot4_url(@calapp).present?
        %li
          = image_tag screenshot4_url(@calapp)
      -if screenshot5_url(@calapp).present?
        %li
          = image_tag screenshot5_url(@calapp)

    %hr

  %h4 Description
  %div
    = @calapp.description
  %hr

  - if @calapp.news and @calapp.news.length > 0
    %h4 News & Updates
    %div
      = @calapp.news
    %hr

  - if @calapp.tag_list and @calapp.tag_list.length > 0
    %div 
      %h4 Tags:
      - @calapp.tag_list.each do |t|
        %span.secondary.round.label
          = link_to t, calapps_path(:tag => t)

    %hr

  %div
    %h4 Reviews
    %ul.small-block-grid-4
      %li
        .panel.callout
          %h5="Average Rating:"
          - if @calapp.rating != 0
            %p= "%.1f" % @calapp.rating.to_s
          - else
            %p No Reviews Yet, Be the first!
    %ul.small-block-grid-3
      - @calapp.reviews.each do |t|
        %li
          .panel
            %p
              -if defined? t.user.name
                %span
                  %b=t.user.name
                  =" | "
                  %i= t.updated_at.strftime("%b %-d, %Y")
              -else
                %span
                  %b="Anonymous"
                  =" | "
                  %i= t.updated_at.strftime("%b %-d, %Y")
            %p
              -(1..t.review_rating).each do |i|
                %i.fi-star
            %p
              ='"'
              =t.review_text
              ='"'
            - if is_admin? 
              = link_to "Delete Review", calapp_review_path(@calapp,:user_id=> t.user.id), :method => "delete",  :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'
            - elsif current_user && Review.where(user_id: current_user.id, calapp_id: current_app).first
              = link_to "Delete My Review", calapp_review_path(@calapp), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'

  -if signed_in? and (berkeley_user? or is_admin?) and not Review.where(user_id: current_user.id, calapp_id: current_app).first
    = link_to 'New Review', new_calapp_review_path(@calapp), :class => "btn btn-primary"
  %hr

  %ul.button-group
    = tweet_button(:text => "Check Out #{@calapp.name} #calapps!", :via => "", :count => "horizontal");

    = like_button(576067885779630)

    = pinit_button
    .g-plusone{"data-annotation".to_sym => "inline", "data-width".to_sym => "300"}

  %hr
  %div
    = link_to t('.back', :default => t("helpers.links.back")), calapps_path, :class => 'btn btn-default'
    - if is_admin? or is_owner?
      = link_to "Edit", edit_calapp_path(@calapp), :class => 'btn btn-primary'
    - if is_admin?
      = link_to "Delete", calapp_path(@calapp), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'
  %hr

  :javascript
    (function() {
      var po = document.createElement('script'); po.type = 'text/javascript'; po.async = true;
      po.src = 'https://apis.google.com/js/platform.js';
      var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(po, s);
    })();