config/routes.rb
Calapps::Application.routes.draw do
  get "password_resets/new"

  get "welcome/about"
  get "welcome/success"
  get "welcome/construction"
  get "users/new"
  get 'tags/:tag', to: 'calapps#index', as: :tag

  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', :to => 'sessions#destroy',     via: :delete
  match 'contact' => 'contact#new', :as => 'contact', :via => :get
  match '/contact' => 'contact#create', :as => 'contact', :via => :post

  resources :users
  
  resources :calapps do
    collection do
      get 'search'
      get 'feed'
    end
    member do
      put 'archive'
      put 'approve'
    end
    resources :reviews, :only => [:create, :new, :destroy]
  end
  
  resources :sessions
  resources :password_resets
  
  root :to => 'calapps#index'

end

app/views/layouts/application.html.haml
!!! 5
%html

  %head

    %title CalApps
    = favicon_link_tag '/favicon.ico'
    = stylesheet_link_tag "http://fonts.googleapis.com/css?family=Open+Sans:300italic,400,300,700,600"
    = stylesheet_link_tag "application"
    = javascript_include_tag "application"
    = csrf_meta_tags

  %body

    #main-menu.navbar

      .navbar-header
        %button.navbar-toggle{:type => "button", "data-toggle" => "collapse", "data-target" => ".navbar-collapse"}
          %span.sr-only Toggle navigation
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar

        = link_to "/", :class => "home-link" do
          /=image_tag calapp logo
          %span.gallery-menu-text
            CalApps Gallery

      .navbar-collapse.collapse
        %ul{:class => "nav navbar-nav navbar-right main-navigation"}

          %li{:class => "tab"}>
            = link_to '/welcome/about' do
              %i{:class => "fa fa-info"}
              %p About

          %li{:class => "tab"}>
            = link_to '/contact' do
              %i{:class => "fa fa-envelope"}
              %p Contact

          - if is_admin?
            %li{:class => "tab"}>
              = link_to feed_calapps_path do
                %i{:class => "fa fa-rss"}
                %p Feed
            %li{:class => "tab"}>
              = link_to users_path do
                %i{:class => "fa fa-user"}
                %p Users  

          - if signed_in?

            %li.dropdown-custom.tab.account
              %a
                %i.fa.fa-user
                %p
                  = current_user.email
                  %b.caret

              %ul.dropdown-menu
                %li
                  = link_to "Profile", edit_user_path(@current_user)
                %li
                  = link_to "Sign out", signout_path, :method => :delete

          - else
            %li{:class => "tab account"}>
              = link_to signup_path do
                %i{:class => "fa fa-user"}
                %p Sign up

            %li{:class => "tab account"}>
              = link_to signin_path do
                %i{:class => "fa fa-book"}
                %p Log In

    - flash.each do |name, msg|
      .flash
        - if not msg.nil?
          - if msg.is_a?(String)
            %div{:class => "alert alert-#{name == :notice ? "success" : "warning"}", :id => "flash"}
              %a.close{"data-dismiss" => "alert"} ×
              = content_tag :div, msg, :id => "flash_#{name}"

    .container
      = yield